from typing import Optional, Protocol
from bson import ObjectId

from src.domain.attachment import Attachment


class AttachmentRepository(Protocol):
  async def upsert(self, attachment: Attachment) -> Attachment: ...
  async def get(self, attachment_id: ObjectId, user_id: ObjectId) -> Optional[Attachment]: ...
  async def list_by_messages(self, user_id: ObjectId, message_ids: list[ObjectId]) -> list[Attachment]: ...
  # los borrados devuelven las claves del bucket: los bytes no se van solos
  async def delete_by_messages(self, user_id: ObjectId, message_ids: list[ObjectId]) -> list[str]: ...
  async def delete_all_by_user(self, user_id: ObjectId) -> list[str]: ...
