from typing import Protocol, Optional
from bson import ObjectId

from src.domain.contact import Contact


class ContactRepository(Protocol):
  async def create(self, contact: Contact) -> Contact: ...
  async def get(self, contact_id: ObjectId, user_id: ObjectId) -> Optional[Contact]: ...
  async def get_by_email(self, user_id: ObjectId, email: str) -> Optional[Contact]: ...
  async def get_by_user(self, user_id: ObjectId, search: Optional[str] = None) -> list[Contact]: ...
  async def update(self, contact_id: ObjectId, user_id: ObjectId, changes: dict) -> Optional[Contact]: ...
  async def delete(self, contact_id: ObjectId, user_id: ObjectId) -> bool: ...
