from typing import Protocol, Optional
from bson import ObjectId

from src.domain.integration import Integration, Provider


class IntegrationRepository(Protocol):
  async def upsert(self, integration: Integration) -> Integration: ...
  async def get_by_user(self, user_id: ObjectId, provider: Provider) -> Optional[Integration]: ...
  async def get_by_account(self, provider: Provider, account_id: str) -> Optional[Integration]: ...
  async def get_by_email(self, provider: Provider, email: str) -> Optional[Integration]: ...
  async def list_by_user(self, user_id: ObjectId) -> list[Integration]: ...
  async def delete(self, integration_id: ObjectId, user_id: ObjectId) -> bool: ...
