from typing import Protocol
from bson import ObjectId

from src.domain.message import Message


class MessageRepository(Protocol):
  async def upsert(self, message: Message) -> Message: ...
  async def list_by_thread_id_user_id(self, user_id: ObjectId, integration_id: ObjectId, thread_id: str) -> list[Message]: ...
  async def list_context(
    self, user_id: ObjectId, integration_id: ObjectId, thread_id: str, addresses: list[str], exclude_provider_id: str, limit: int
  ) -> list[Message]: ...
  async def ids_by_integration(self, user_id: ObjectId, integration_id: ObjectId) -> list[ObjectId]: ...
  async def ids_older_than(self, internal_date: int) -> dict[ObjectId, list[ObjectId]]: ...
  async def delete(self, message_id: ObjectId, user_id: ObjectId) -> bool: ...
  async def delete_many(self, user_id: ObjectId, message_ids: list[ObjectId]) -> int: ...
  async def delete_all_by_user(self, user_id: ObjectId) -> int: ...
