from typing import Optional, Protocol

from bson import ObjectId

from src.domain.organization import Invitation, Organization
from src.domain.user import User


class OrganizationRepository(Protocol):
  async def create(self, organization: Organization) -> Organization: ...
  async def get(self, organization_id: ObjectId) -> Optional[Organization]: ...
  async def update(self, organization_id: ObjectId, changes: dict) -> Optional[Organization]: ...
  async def delete(self, organization_id: ObjectId) -> bool: ...
  async def list_members(self, organization_id: ObjectId) -> list[User]: ...


class InvitationRepository(Protocol):
  async def upsert(self, invitation: Invitation) -> Invitation: ...
  async def get_for_email(self, invitation_id: ObjectId, email: str) -> Optional[Invitation]: ...
  async def list_by_org(self, organization_id: ObjectId) -> list[Invitation]: ...
  async def list_by_email(self, email: str) -> list[Invitation]: ...
  async def delete(self, invitation_id: ObjectId, filter: dict) -> bool: ...
  async def delete_by_org(self, organization_id: ObjectId) -> None: ...
