from typing import Protocol


class Storage(Protocol):
  async def put(self, key: str, data: bytes, content_type: str) -> str: ...
  async def delete(self, keys: list[str]) -> None: ...
  async def signed_url(self, key: str, filename: str, expires_in: int = 3600) -> str: ...
