from typing import Protocol, Optional
from bson import ObjectId

from src.domain.task import Task, Status


class TaskRepository(Protocol):
  async def upsert(self, task: Task) -> Task: ...
  async def get(self, task_id: ObjectId, user_id: ObjectId) -> Optional[Task]: ...
  async def get_by_thread(self, user_id: ObjectId, thread_id: str) -> Optional[Task]: ...
  async def get_by_user(self, user_id: ObjectId, status: Optional[Status] = None) -> list[Task]: ...
  async def update(self, task_id: ObjectId, user_id: ObjectId, changes: dict) -> Optional[Task]: ...
  async def delete(self, task_id: ObjectId, user_id: ObjectId) -> bool: ...
  async def delete_all_by_user(self, user_id: ObjectId) -> int: ...
