from typing import Protocol, Optional
from bson import ObjectId

from src.domain.user import AuthProvider, User


class UserRepository(Protocol):
  async def create(self, user: User) -> User: ...
  async def get(self, user_id: ObjectId) -> Optional[User]: ...
  async def get_by_email(self, email: str) -> Optional[User]: ...
  async def get_by_auth_account(
    self, auth_provider: AuthProvider, auth_account_id: str
  ) -> Optional[User]: ...
  async def list(self) -> list[User]: ...
  async def update(self, user_id: ObjectId, changes: dict) -> Optional[User]: ...
  async def delete(self, user_id: ObjectId) -> bool: ...
